version: 2
updates:
  # Dependabot para Python (Backend)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Dependabot para Node.js (Frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Dependabot para Docker (Imagens e compose)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
